### ISSUE TITLE
Tree shaking in dev

### ISSUE THREAD

**Issue by oligriffiths** [kellyselden/ember-cli-tree-shaker#10]
Do you plan to perform tree shaking in dev?

I’m wondering for things that are removed if it’s worth adding some kind of stub that outputs a meaningful error in the console of a tree-shaken dependency IS referenced in the running app, say for things like the google analytics manual override from the readme? Otherwise you’ll get a “module doesn’t exit” type error that will be super hard to track down if it’s the add on code or the tree shaking.

**Comment by kellyselden** [comment]
> Do you plan to perform tree shaking in dev?

I don't understand what you mean. We make no assumption what environment you are building.

As for notifying when a eliminated module is used, that probably won't work. If it has a direct import and was eliminated, then we have a bug that is easily fixed. If it is an indirect link, then we probably have no way to match them to show the warning. For example, if `addon-tree-output/ember-something/services/foo.js` was eliminated, and our app at runtime says something like "tried to inject service 'foo' but none found", we have to do some serious guessing to determine which module matches up with that error.

**Comment by kellyselden** [comment]
Closing for now.
