### ISSUE TITLE
Document how to measure results

### ISSUE THREAD

**Issue by danwenzel** [kellyselden/ember-cli-tree-shaker#18]
It would be nice if the README indicated how exactly to measure the results of tree shaking.  How do you measure how many modules were removed, file size reduction, etc?

**Comment by kellyselden** [comment]
It prints to the console how many and which one's were removed.

**Comment by danwenzel** [comment]
Ah, I see that now.  :)  Maybe add that info to the README?  Any other ways to measure?

**Comment by kellyselden** [comment]
you can do a production build before and after, the sizes are printed to console.

**Comment by kellyselden** [comment]
feel free to submit a PR with wording.

**Comment by danwenzel** [comment]
will do.  Thank you!

**Comment by danwenzel** [comment]
https://github.com/kellyselden/ember-cli-tree-shaker/pull/19
